### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by kapil-rss** [Kommunicate-io/Kommunicate-Web-SDK#520]
How can we configure SSL?

**Comment by ab14bhardwaj** [comment]
@kapil-rss 
That will be done from your end, you can consult your dev-ops team regarding the same.

**Comment by kapil-rss** [comment]
Thanks Abhinav. We have made the required changes.


Regards
Kapil
02031987365
________________________________

**Comment by ab14bhardwaj** [comment]
The issue is resolved.
Closing this issue.
