### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by benharvie** [Kommunicate-io/Kommunicate-Web-SDK#989]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@riteshgohil) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Sanjeevsinghnegi** [comment]
Hello there,
I am Sanjeev from kommunicate, I am going to add the `SECURITY.md` file meanwhile, you can share all the details on security@kommunicate.io email address.

Thanks, 
Sanjeev Singh

**Comment by riteshgohil** [comment]
Thank you for the email address.
Kindly check your email, I have sent the vulnerability to you.
Thank you
